name: Publish Range Utils  to npm

on:
  release:
    types: [published] # Déclenché quand une release GitHub est publiée

jobs:
  publish:
    name: 📦 Publish to npm
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write # nécessaire pour npm publish avec provenance

    steps:
      - name: 🧾 Checkout code
        uses: actions/checkout@v4

      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          registry-url: "https://registry.npmjs.org/"

      - name: 📥 Install dependencies
        run: npm ci

      - name: 🧪 Run build (optionnel si tu as un script build)
        run: npm run build

      - name: 🚀 Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
